# Generated by Django 5.2.10 on 2026-02-02 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_course_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='student',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
